name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run a test step
        run: echo "Hello, CI is working!"
      - name: Run a test step
        run: |
          echo "This run should fail"
          exit 1